In [1]:
import pandas as pd
import numpy as np

import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.utils import make_grid

import math
import random

from PIL import Image, ImageOps, ImageEnhance
import numbers

import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
batch_size_train = 64
batch_size_test = 1000
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5,), (0.5,))])

train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=True, download=True,
                             transform=transform),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=False, download=True,
                             transform=transform),
  batch_size=batch_size_test, shuffle=True)

torch.Size([64, 10])


In [7]:
Hcriterion = nn.MSELoss()
examples = enumerate(test_loader)
batch_idx, (example_data, example_targets) = next(examples)
nb_digits = 10
target_onehot = torch.FloatTensor(data.shape[0], nb_digits)
output = torch.zeros([data.shape[0],10], dtype = torch.float64)

tensor([1., 1., 1.], dtype=torch.float64)

In [7]:
x = torch.ones(1, requires_grad=True)
print(x)

tensor([1.], requires_grad=True)


In [22]:
gamma = torch.ones(1, requires_grad=True, dtype = torch.double)
optimizer = optim.Adam([gamma], lr=0.003)
criterion = nn.MSELoss()

output = torch.tensor([[-2.4197e+01, -1.6696e+01, -4.9090e+00, -2.3021e+00, -1.1464e+01,
         -1.0789e+01, -1.4716e+01, -1.2182e+01,  2.1967e+01, -6.7910e+00],[ 3.5568e+01,  2.6038e+01,  6.2582e+00, -2.5737e-01,  1.2279e+01,
          8.8739e+00,  1.8718e+01,  1.7147e+01, -2.2834e+01,  2.0158e+00]])
temp = torch.tensor([[ 3.5568e+01,  2.6038e+01,  6.2582e+00, -2.5737e-01,  1.2279e+01,
          8.8739e+00,  1.8718e+01,  1.7147e+01, -2.2834e+01,  2.0158e+00]])
one_hot = torch.DoubleTensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

output = F.softmax(output, dim = 1)
print(output)
print(torch.sum(output[0]))
predicted = output + gamma * temp
loss = criterion(predicted, one_hot)
print("1:", gamma)
print("gamma gradient:", gamma.retain_grad())
loss.backward()
print("2:", gamma)
optimizer.step()
print("3:", gamma)

tensor([[8.9378e-21, 1.6176e-17, 2.1277e-12, 2.8845e-11, 3.0276e-15, 5.9464e-15,
         1.1716e-16, 1.4767e-15, 1.0000e+00, 3.2401e-13],
        [9.9993e-01, 7.2634e-05, 1.8659e-13, 2.7619e-16, 7.6857e-11, 2.5519e-12,
         4.8096e-08, 9.9961e-09, 4.3281e-26, 2.6818e-15]])
tensor(1.)
1: tensor([1.], dtype=torch.float64, requires_grad=True)
gamma gradient: None
2: tensor([1.], dtype=torch.float64, requires_grad=True)
3: tensor([0.9970], dtype=torch.float64, requires_grad=True)


C:\Users\cozyn\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:445: UserWarning: Using a target size (torch.Size([1, 10])) that is different to the input size (torch.Size([2, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
